package Lesson06;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Arc2D;

/**
 * Created by Dzung on 10/9/2016.
 */
public class Bai1 {
    private JPanel pnlContent;
    private JTextField txtF;
    private JTextField txtC;
    private JButton btnCal;
    private JButton btnCont;
    private JButton btnExit;
    private JPanel pnlBtns;
    private JLabel lblF;
    private JLabel lblC;
    private JPanel pnlInput;

    public Bai1() {
        JFrame frame = new JFrame();
        frame.setLocationRelativeTo(null);
        frame.setSize(330, 250);
        frame.setContentPane($$$getRootComponent$$$());
        frame.setTitle("Chuyển nhiệt độ giữa C và F");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        handler();
    }

    private void handler() {
        btnCal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    if (!txtF.getText().equals("")) {
                        double f = Float.parseFloat(txtF.getText());
                        txtC.setText(String.valueOf((f - 32) / 1.8));
                    } else if (!txtC.getText().equals("")) {
                        double c = Float.parseFloat(txtC.getText());
                        txtF.setText(String.valueOf((c * 1.8) + 32));
                    } else {
                        JOptionPane.showMessageDialog(pnlContent, "Xin nhập ít nhất 1 trường", "Chưa nhập dữ liệu", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(pnlContent, "Xin nhập số", "Nhập sai kiểu", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        btnCont.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                txtC.setText("");
                txtF.setText("");
            }
        });

        btnExit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlContent = new JPanel();
        pnlContent.setLayout(new BorderLayout(0, 0));
        pnlInput = new JPanel();
        pnlInput.setLayout(new GridBagLayout());
        pnlContent.add(pnlInput, BorderLayout.CENTER);
        lblF = new JLabel();
        lblF.setText("Nhập vào độ F");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        pnlInput.add(lblF, gbc);
        txtF = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlInput.add(txtF, gbc);
        lblC = new JLabel();
        lblC.setText("Độ C tương tự");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        pnlInput.add(lblC, gbc);
        txtC = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlInput.add(txtC, gbc);
        pnlBtns = new JPanel();
        pnlBtns.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pnlContent.add(pnlBtns, BorderLayout.SOUTH);
        btnCal = new JButton();
        btnCal.setText("Tính");
        pnlBtns.add(btnCal);
        btnCont = new JButton();
        btnCont.setText("Tiếp tục");
        pnlBtns.add(btnCont);
        btnExit = new JButton();
        btnExit.setText("Thoát");
        pnlBtns.add(btnExit);
        lblF.setLabelFor(txtF);
        lblC.setLabelFor(txtC);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlContent;
    }
}
