package Lesson06;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.*;

/**
 * Created by Dzung on 10/9/2016.
 */
public class Bai2 {
    private JPanel pnlContent;
    private JTextArea txtInput;
    private JCheckBox ckbBold;
    private JCheckBox ckbItalic;
    private JPanel pnlCkbs;

    public Bai2() {
        JFrame frame = new JFrame();
        frame.setLocationRelativeTo(null);
        frame.setSize(350, 210);
        frame.setContentPane($$$getRootComponent$$$());
        frame.setTitle("Đổi phông chữ");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        handler();

    }

    private void handler() {
        txtInput.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                txtInput.setText("");
            }
        });
        final String fontName = "Time News Roman";
        txtInput.setFont(new Font(fontName, Font.PLAIN, 16));
        ckbBold.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                setFont(fontName);
            }
        });

        ckbItalic.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                setFont(fontName);
                System.out.println(e.getStateChange());
            }
        });
    }

    private void setFont(String fontName) {
        Font normal = new Font(fontName, Font.PLAIN, 16);
        Font bold = new Font(fontName, Font.BOLD, 16);
        Font italic = new Font(fontName, Font.ITALIC, 16);
        Font boldItalic = new Font(fontName, Font.BOLD + Font.ITALIC, 16);
        if (ckbBold.isSelected() && !ckbItalic.isSelected()) {
            txtInput.setFont(bold);
        } else if (ckbBold.isSelected() && ckbItalic.isSelected()) {
            txtInput.setFont(boldItalic);
        } else if (!ckbBold.isSelected() && ckbItalic.isSelected()) {
            txtInput.setFont(italic);
        } else {
            txtInput.setFont(normal);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlContent = new JPanel();
        pnlContent.setLayout(new BorderLayout(0, 0));
        pnlCkbs = new JPanel();
        pnlCkbs.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pnlContent.add(pnlCkbs, BorderLayout.SOUTH);
        ckbBold = new JCheckBox();
        ckbBold.setText("Bold");
        pnlCkbs.add(ckbBold);
        ckbItalic = new JCheckBox();
        ckbItalic.setText("Italic");
        pnlCkbs.add(ckbItalic);
        txtInput = new JTextArea();
        txtInput.setEnabled(true);
        txtInput.setText("Nhập vào để kiểm tra");
        pnlContent.add(txtInput, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlContent;
    }
}
