/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise6;

import java.awt.Font;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author User
 */
public class ex2 extends javax.swing.JFrame {

    /**
     * Creates new form ex2
     */
    public ex2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfFont = new javax.swing.JTextField();
        cbBold = new javax.swing.JCheckBox();
        cbItalic = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfFont.setEditable(false);
        tfFont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFont.setText("Watch the font style change");

        cbBold.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbBold.setText("Bold");
        cbBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoldActionPerformed(evt);
            }
        });

        cbItalic.setText("Italic");
        cbItalic.setToolTipText("");
        cbItalic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbItalicMouseClicked(evt);
            }
        });
        cbItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItalicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfFont, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(cbBold)
                        .addGap(29, 29, 29)
                        .addComponent(cbItalic)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbBold, cbItalic});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBold)
                    .addComponent(cbItalic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoldActionPerformed
        if(cbBold.isSelected() && cbItalic.isSelected()){
            tfFont.setFont(new Font("Tahoma", 3, 11));
        }else if((!cbBold.isSelected()) && cbItalic.isSelected()){
            tfFont.setFont(new Font("Tahoma", 2, 11));
        }else if(cbBold.isSelected() && (!cbItalic.isSelected())){
            tfFont.setFont(new Font("Tahoma", 1, 11));
        }else if((!cbBold.isSelected()) && (!cbItalic.isSelected())){
            tfFont.setFont(new Font("Tahoma", 0, 11));
        }
    }//GEN-LAST:event_cbBoldActionPerformed

    private void cbItalicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbItalicMouseClicked
        
    }//GEN-LAST:event_cbItalicMouseClicked

    private void cbItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItalicActionPerformed
        if(cbBold.isSelected() && cbItalic.isSelected()){
            tfFont.setFont(new Font("Tahoma", 3, 11));
        }else if((!cbBold.isSelected()) && cbItalic.isSelected()){
            tfFont.setFont(new Font("Tahoma", 2, 11));
        }else if(cbBold.isSelected() && (!cbItalic.isSelected())){
            tfFont.setFont(new Font("Tahoma", 1, 11));
        }else if((!cbBold.isSelected()) && (!cbItalic.isSelected())){
            tfFont.setFont(new Font("Tahoma", 0, 11));
        }
    }//GEN-LAST:event_cbItalicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbBold;
    private javax.swing.JCheckBox cbItalic;
    private javax.swing.JTextField tfFont;
    // End of variables declaration//GEN-END:variables
}
