/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiAwt;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Exercise1 extends javax.swing.JFrame {

    /**
     * Creates new form Exercise1
     */
    public Exercise1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbketqua = new javax.swing.JLabel();
        jtfx = new javax.swing.JTextField();
        jtfy = new javax.swing.JTextField();
        jbtcong = new javax.swing.JButton();
        jbttru = new javax.swing.JButton();
        jbtnhan = new javax.swing.JButton();
        jbtchia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Number X:");
        jLabel1.setToolTipText("");

        jLabel2.setText("Number Y:");

        jlbketqua.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jlbketqua.setText("kết quả");

        jtfx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfxActionPerformed(evt);
            }
        });

        jbtcong.setText("+");
        jbtcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcongActionPerformed(evt);
            }
        });

        jbttru.setText("-");
        jbttru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttruActionPerformed(evt);
            }
        });

        jbtnhan.setText("*");
        jbtnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhanActionPerformed(evt);
            }
        });

        jbtchia.setText("/");
        jbtchia.setMaximumSize(new java.awt.Dimension(37, 23));
        jbtchia.setMinimumSize(new java.awt.Dimension(37, 23));
        jbtchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtchiaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("bài tập số 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtcong, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbttru, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfy, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfx, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtchia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jlbketqua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtchia, jbtcong, jbtnhan, jbttru});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtfx, jtfy});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtcong)
                    .addComponent(jbttru)
                    .addComponent(jbtnhan)
                    .addComponent(jbtchia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlbketqua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtfx, jtfy});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtchia, jbtcong, jbtnhan, jbttru});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfxActionPerformed

    private void jbtcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcongActionPerformed
        String number1 = jtfx.getText();
        String number2 = jtfy.getText();
        double num1 = 0;
        double num2 = 0;
        double temp = 0;
        try {
            num1 = Integer.parseInt(jtfx.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfx.requestFocus();
            return;
        }
        try {
            num2 = Integer.parseInt(jtfy.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfx.requestFocus();
            return;
        }

        temp = num1 + num2;
        jlbketqua.setForeground(Color.blue);
        jlbketqua.setText(new Double(temp).toString());
    }//GEN-LAST:event_jbtcongActionPerformed

    private void jbttruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttruActionPerformed
        String number1 = jtfx.getText();
        String number2 = jtfy.getText();
        double num1 = 0;
        double num2 = 0;
        double temp;
        try {
            num1 = Integer.parseInt(jtfx.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfx.requestFocus();
            return;
        }
        try {
            num2 = Integer.parseInt(jtfy.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfy.requestFocus();
            return;
        }

        temp = num1 - num2;
        jlbketqua.setForeground(Color.blue);
        jlbketqua.setText(new Double(temp).toString());
    }//GEN-LAST:event_jbttruActionPerformed

    private void jbtnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhanActionPerformed
        String number1 = jtfx.getText();
        String number2 = jtfy.getText();
        double num1 = 0;
        double num2 = 0;
        double temp = 0;
        try {
            num1 = Integer.parseInt(jtfx.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfx.requestFocus();
            return;
        }
        try {
            num2 = Integer.parseInt(jtfy.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfy.requestFocus();
            return;
        }
        
        temp = num1 * num2;
        jlbketqua.setForeground(Color.blue);
        jlbketqua.setText(new Double(temp).toString());
    }//GEN-LAST:event_jbtnhanActionPerformed

    private void jbtchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtchiaActionPerformed
        String number1 = jtfx.getText();
        String number2 = jtfy.getText();
        double num1 = 0;
        double num2 = 0;

        try {
            num1 = Integer.parseInt(jtfx.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfx.requestFocus();
            return;
        }
        try {
            num2 = Integer.parseInt(jtfy.getText().toString());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai kiểu");
            jtfy.requestFocus();
            return;
        }
        
        if (num2 == 0) {
                jlbketqua.setForeground(Color.red);
                jlbketqua.setText("không chia được");
                JOptionPane.showMessageDialog(null, "không chia được cho 0");
                jtfy.requestFocus();
            } else {
                double sum = 0;
                
                sum = num1 / num2;
                jlbketqua.setForeground(Color.blue);
                jlbketqua.setText(new Double(sum).toString());
            }
    }//GEN-LAST:event_jbtchiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Exercise1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtchia;
    private javax.swing.JButton jbtcong;
    private javax.swing.JButton jbtnhan;
    private javax.swing.JButton jbttru;
    private javax.swing.JLabel jlbketqua;
    private javax.swing.JTextField jtfx;
    private javax.swing.JTextField jtfy;
    // End of variables declaration//GEN-END:variables
}
