/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiAwt;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class Exercise2 extends javax.swing.JFrame {

    /**
     * Creates new form Exercise2
     */
    public Exercise2() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbmau = new javax.swing.JLabel();
        rbBlack = new javax.swing.JRadioButton();
        rbBlue = new javax.swing.JRadioButton();
        rbRed = new javax.swing.JRadioButton();
        rbGreen = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbBlack);
        rbBlack.setText("Black");
        rbBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlackActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBlue);
        rbBlue.setText("Blue");
        rbBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlueActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbRed);
        rbRed.setText("Red");
        rbRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRedActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbGreen);
        rbGreen.setText("Green");
        rbGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbGreen)
                    .addComponent(rbBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbRed, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(lbmau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbBlack, rbBlue, rbGreen, rbRed});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBlue)
                .addGap(6, 6, 6)
                .addComponent(rbGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbmau, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbBlack, rbBlue, rbGreen, rbRed});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlackActionPerformed
        if(rbBlack.isSelected()){
            lbmau.setOpaque(true);
            lbmau.setBackground(Color.black);
            lbmau.setHorizontalAlignment(JLabel.CENTER);
            lbmau.setForeground(Color.green);
            lbmau.setText("Black is selected");
        }
    }//GEN-LAST:event_rbBlackActionPerformed

    private void rbGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGreenActionPerformed
        if(rbGreen.isSelected()){
            lbmau.setOpaque(true);
            lbmau.setBackground(Color.green);
            lbmau.setHorizontalAlignment(JLabel.CENTER);
            lbmau.setForeground(Color.blue);
            lbmau.setText("Green is selected");
        }
    }//GEN-LAST:event_rbGreenActionPerformed

    private void rbBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlueActionPerformed
        if(rbBlue.isSelected()){
            lbmau.setOpaque(true);
            lbmau.setBackground(Color.blue);
            lbmau.setHorizontalAlignment(JLabel.CENTER);
            lbmau.setForeground(Color.red);
            lbmau.setText("Blue is selected");
        }
    }//GEN-LAST:event_rbBlueActionPerformed

    private void rbRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRedActionPerformed
        if(rbRed.isSelected()){
            
            lbmau.setOpaque(true);
            lbmau.setBackground(Color.red);
            lbmau.setHorizontalAlignment(JLabel.CENTER);
            lbmau.setForeground(Color.black);
            lbmau.setText("Red is selected");
        }
    }//GEN-LAST:event_rbRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercise2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbmau;
    private javax.swing.JRadioButton rbBlack;
    private javax.swing.JRadioButton rbBlue;
    private javax.swing.JRadioButton rbGreen;
    private javax.swing.JRadioButton rbRed;
    // End of variables declaration//GEN-END:variables
}
