/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitap;

import java.awt.event.ItemEvent;

/**
 *
 * @author TLC
 */
public class thay_doi_kieu_chu extends javax.swing.JFrame {
    int a=0;
    int b=0;
        /**
     * 
     */
    public thay_doi_kieu_chu() {
        initComponents();
        tfFont.setFont(new java.awt.Font("Times New Roman", a+b, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfFont = new javax.swing.JTextField();
        cbBold = new javax.swing.JCheckBox();
        cbItatic = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Thay đổi kiểu chữ");

        tfFont.setToolTipText("nhập vào một chuỗi");

        cbBold.setText("bold");
        cbBold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBoldItemStateChanged(evt);
            }
        });

        cbItatic.setText("Italic");
        cbItatic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItaticItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(cbBold)
                .addGap(44, 44, 44)
                .addComponent(cbItatic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfFont)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfFont, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBold)
                    .addComponent(cbItatic))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBoldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBoldItemStateChanged
//       if(cbBold.isSelected()==true){
//           tfFont.setFont(new java.awt.Font("Times New Roman", 1, 18));
//       }
//       if(cbBold.isSelected()==false){
//           tfFont.setFont(new java.awt.Font("Times New Roman", 0, 18));
//       }
//       if(cbItatic.isSelected()==true){
//           tfFont.setFont(new java.awt.Font("Times New Roman", 1, 18));
//       }
//       if(cbItatic.isSelected()==false){
//           tfFont.setFont(new java.awt.Font("Times New Roman", 0, 18));
//       }
       
        if(evt.getStateChange()==ItemEvent.SELECTED){
            a=1;
            tfFont.setFont(new java.awt.Font("Times New Roman", a+b, 18));
            
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
           a=0;
            tfFont.setFont(new java.awt.Font("Times New Roman", a+b, 18));
        }
       
    }//GEN-LAST:event_cbBoldItemStateChanged

    private void cbItaticItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItaticItemStateChanged
       if(evt.getStateChange()==ItemEvent.SELECTED){
           b=2;
            tfFont.setFont(new java.awt.Font("Times New Roman", a+b, 18));
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            b=0;
            tfFont.setFont(new java.awt.Font("Times New Roman", a+b, 18));
        }
    }//GEN-LAST:event_cbItaticItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thay_doi_kieu_chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thay_doi_kieu_chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thay_doi_kieu_chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thay_doi_kieu_chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thay_doi_kieu_chu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbBold;
    private javax.swing.JCheckBox cbItatic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfFont;
    // End of variables declaration//GEN-END:variables
}
